apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
  - 172.17.255.200-172.17.255.250 # IP range for the load balancer, in this case the ips corresponds to the range of the docker network
  # You can know your docker network range with the command: docker network inspect bridge

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example-l2ad
  namespace: metallb
spec:
  ipAddressPools:
  - first-pool
